title: Rachit Jain # your name (or website title) here
logo: "/images/profile_pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p align="center">
    Master of Business Analytics, MIT
    <br>
    B.Tech, IIT Delhi
    <br><br>
    <img src="images/linkedin_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/rachit1jain/">rachit1jain</a> 
    <br>
    <img src="images/github_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://github.com/rachit-0032/">rachit-0032</a> 
    <br>
    <br>
    <img src="https://github.com/rachit-0032/rachit-0032.github.io/blob/master/images/iitd_logo.png?raw=true" width="30%" height="30%"/>
    <img src="https://github.com/rachit-0032/rachit-0032.github.io/blob/master/images/mit_logo.png?raw=true" width="30%" height="30%"/>
  </p>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3VMTJHPSDJ # your Google Analytics tracking ID here
