title: Nagarjuna Chidarala # your name (or website title) here
logo: "/images/LinkedInDP.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <p align="center">
    Master of Business Analytics and Information Management, Purdue University
    <br>
    Post Graduate Diploma in Management (MBA - Business Analytics), NMIMS Mumbai
    <br>
    B.Tech in Electronics and Communication, IIIT Sricity
    <br><br>
    <img src="images/linkedin_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://www.linkedin.com/in/nagarjunachidara/">nagarjunachidara</a> 
    <br>
    <img src="images/github_logo.png?raw=true" width="5%" height="5%"/>
    <a href="https://github.com/nag96/">nag96</a> 
    <br>
    <br>
    <img src="https://github.com/nag96/nchidara.github.io/blob/master/images/iiits_logo.png?raw=true" width="30%" height="30%"/>
    <img src="https://github.com/nag96/nchidara.github.io/blob/master/images/nm_logo.jpeg?raw=true" width="30%" height="30%"/>
    <img src="https://github.com/nag96/nchidara.github.io/blob/master/images/purdue_logo.png?raw=true" width="30%" height="30%"/>
  </p>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-3VMTJHPSDJ # your Google Analytics tracking ID here
